on:
  workflow_dispatch: 
   inputs:
      version:
        description: '版本号'
        required: true  
        default: '1.0.0'
        type: string
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: mcio-dev/upload-to-nexusmc@v1
        with:
          api_token: ${{ secrets.NEXUSMC_API_TOKEN }}
          resource_id: ${{ vars.NEXUSMC_RESOURCE_ID }}
          version: ${{ inputs.version }}
          files: |
            [
              {
                "path": ".github/workflows/nexusmc.yml",
                "isPrimary": true,
                "loaderIds": ["neoforge"],
                "gameVersions": ["26.1", "26.1.1", "26.1.2"]
              },
              {
                "path": "LICENSE",
                "loaderIds": ["fabric"],
                "gameVersions": ["26.1", "26.1.1", "26.1.2"]
              }
            ]
